name: KHK
favicon: null
layout_spectrum: 0.49818
typography_spectrum: 0.5951123284175992
title: KINKY HONG KONG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.019213820109143853
  lightness: 0.5347426966764033
  saturation: 0.16923461691476405
  rhythmicContrast: 0.18318715482018888
purpose: []
